Repository epiforecasts/covidregionaldata, pull requests merged in 2021-03, with the labels that each got.

#182 Added progress messages for Mexico download.
  R/Mexico.R
Labels: bug

#186 177 change region to data
  NEWS.md
  R/CountryTemplate.R
  R/ECDC.R
  R/Germany.R
  R/Italy.R
  R/Mexico.R
  R/UK.R
  R/WHO.R
  R/get_national_data.R
  R/shared-methods.R
  man/get_region_codes.Rd
Labels: bug

#185 Adds deprecated args for get_regional_data
  DESCRIPTION
  NAMESPACE
  R/get_regional_data.R
  inst/WORDLIST
  man/figures/lifecycle-archived.svg
  man/figures/lifecycle-defunct.svg
  man/figures/lifecycle-deprecated.svg
  man/figures/lifecycle-experimental.svg
  man/figures/lifecycle-maturing.svg
  man/figures/lifecycle-questioning.svg
  man/figures/lifecycle-stable.svg
  man/figures/lifecycle-superseded.svg
  man/get_regional_data.Rd
Labels: bug

#188 add Rmd README + bug fix
  .Rbuildignore
  .gitignore
  NEWS.md
  R/get_national_data.R
  README.Rmd
  README.md
  inst/WORDLIST
  man/figures/README-g7_plot-1.png
  man/figures/README-uk_plot-1.png
  man/figures/README-utla_plot-1.png
Labels: documentation

#193 Added default clean in shared methods.
  R/shared-methods.R
  man/get_region_codes.Rd
Labels: enhancement

#196 Verbose handling
  DESCRIPTION
  NAMESPACE
  R/CountryTemplate.R
  R/ECDC.R
  R/Germany.R
  R/Italy.R
  R/Mexico.R
  R/UK.R
  R/WHO.R
  R/get_national_data.R
  R/get_regional_data.R
  R/shared-methods.R
  R/utils.R
  data-raw/region_codes.R
  inst/WORDLIST
  man/csv_reader.Rd
  man/csv_readr.Rd
  man/message_verbose.Rd
  tests/testthat/custom_data/UK_level_1.rds
  tests/testthat/custom_data/WHO_level_1.rds
  tests/testthat/custom_data/mtcars.csv
  tests/testthat/custom_tests/test-regional-dataset.R
  tests/testthat/test-csv_reader.R
  tests/testthat/test-message_verbose.R
Labels: enhancement

#195 Fix Italy warning
  R/Italy.R
Labels: bug

#184 153 r6 tests - Tests for R6 class
  tests/testthat/test-check_country_class.R
  tests/testthat/test-country_R6_objects.R
Labels: enhancement, help wanted

#204 Check class bugfix 203
  tests/testthat/test-check_country_class.R
Labels: bug
